### ISSUE TITLE
fdaemon: fix urljoin() to be more robust

### ISSUE THREAD

**Issue by pdelsante** [thugs-rumal/rumal#17]
As per #16, `urljoin()` is now using `posixpath.join()` to join URL tokens. This works only when the second argument does not start with a slash `/` - if it does, the first argument will be completely ignored.

To reproduce:

```
# ipython 
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
IPython 1.2.1 -- An enhanced Interactive Python.

In [1]: import posixpath

In [2]: posixpath.join('http://www.test.com/', '/path/to/file')
Out[2]: '/path/to/file'

In [3]: posixpath.join('http://www.test.com/', 'path/to/file')
Out[3]: 'http://www.test.com/path/to/file'

In [4]: posixpath.join('http://www.test.com', '/path/to/file')
Out[4]: '/path/to/file'

In [5]: posixpath.join('http://www.test.com', 'path/to/file')
Out[5]: 'http://www.test.com/path/to/file'
```

Will need to fix `urljoin()` to work even when the second argument starts with `/`.

**Comment by Dennisparchkov** [comment]
PR #31 RabbitMQ communication no longer uses `urljoin()` in `fdaemon.py`
