### ISSUE TITLE
Task Status always is queued up and never gets completed..

### ISSUE THREAD

**Issue by scorpionhiccup** [thugs-rumal/rumal#2]
Result of the task is not being displayed and the status doesn't change.

> All the tasks are lined up in the queue but not executed.   

PS: Working behind proxy

**Comment by scorpionhiccup** [comment]
Possible reason maybe because of proxy as in the results it shows proxy None for all the requests...

**Comment by scorpionhiccup** [comment]
Yep, the Ticket Error is gone now but the task status still shows queued even on adding the appropriate proxy..Any reasons as to why this maybe happening?

**Comment by pdelsante** [comment]
The reason why the status never moves from "queued" is that there is still no backend that may process the analysis, that's one of the things that GSoC students will hopefully do B-)

If you want to play with some real data, you should run Thug by hand and then import its results by using `test_utils/import_existing_results.py`.

**Comment by scorpionhiccup** [comment]
Oh okay :+1:
