### ISSUE TITLE
Auto-scroll Up in Panels

### ISSUE THREAD

**Issue by reachtarunhere** [thugs-rumal/rumal#22]
https://github.com/thugs-rumal/rumal/blob/master/templates/static/js/real_setPanels.js needs some fixing up.

The Panels on the left often hold content larger then their max size. When the panels collapse the the div should automatically scroll up once the hover is removed. The code for auto scrolling is present but is not working.

**Comment by Dennisparchkov** [comment]
Fixed in #37
