### ISSUE TITLE
Codes panel -> view for files not working

### ISSUE THREAD

**Issue by PrateekGupta1509** [thugs-rumal/rumal#24]
On selecting a node , the view buttons in the table for Codes Panel does not work.
![s3](https://cloud.githubusercontent.com/assets/12897605/13554286/ccdc5594-e3c9-11e5-8495-e5142d72e4da.png)

**Comment by pdelsante** [comment]
You are absolutely right. I think the code opening the details has not actually been implemented yet, and the links are there only to evaluate what the overall look and feel.

Maybe @reachtarunhere may confirm this?

**Comment by PrateekGupta1509** [comment]
I went through the code and the details are actually presented in lightbox but the opening function for that doesn't seem to work due to a javascript error.
I would like to assign this issue to myself.

**Comment by reachtarunhere** [comment]
@PrateekGupta1509  is correct the implementation is present but is throwing a JS error. For some reason the function is not being called.

**Comment by pdelsante** [comment]
Fixed by #25
