### ISSUE TITLE
My Scans page: Incorrect href values in table of starred scans 

### ISSUE THREAD

**Issue by satwik77** [thugs-rumal/rumal#26]
**Issue**
The links in the page of starred scans `templates/interface/myscans2.html` are incorrect. The first column containing the ids should lead to the corresponding report page for the scanned url but the link appends the id to the current url of the page. The second column containing the urls of the pages which were starred behaves similarly.

**Comment by Dennisparchkov** [comment]
Fixed in #35. It is not a good idea to make the url fields a href. We do not want users to click on the potentially malicious websites. This issue can be closed. PR #27 can be closed
