### ISSUE TITLE
Mistake in short description of TaskAdmin Actions

### ISSUE THREAD

**Issue by reachtarunhere** [thugs-rumal/rumal#6]
I have made a fix in my pull request :) 
![screenshot from 2015-03-21 07 38 16](https://cloud.githubusercontent.com/assets/9061913/6763339/baaedffe-cf9d-11e4-801a-11d596bc6316.png)

**Comment by scorpionhiccup** [comment]
Thanks for pointing out that mistake I guess I overlooked it.. :thumbsup:
